// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGHSS.Api.Data;

#nullable disable

namespace SGHSS.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410004125_AddPerfilUsuario")]
    partial class AddPerfilUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SGHSS.Api.Models.Agendamento", b =>
                {
                    b.Property<int>("IdAgendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAgendamento"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCriadoPorUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int>("IdProfissionalSaude")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorConsulta")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdAgendamento");

                    b.HasIndex("IdCriadoPorUsuario");

                    b.HasIndex("IdPaciente");

                    b.HasIndex("IdProfissionalSaude");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Paciente", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<string>("NumeroCartaoSUS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSanguineo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPaciente");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPagamento"));

                    b.Property<DateTime>("DataHoraPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FormaPagamento")
                        .HasColumnType("int");

                    b.Property<int>("IdAgendamento")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorPago")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPagamento");

                    b.HasIndex("IdAgendamento")
                        .IsUnique();

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Pessoa", b =>
                {
                    b.Property<int>("IdPessoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPessoa"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPessoa");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("SGHSS.Api.Models.ProfissionalSaude", b =>
                {
                    b.Property<int>("IdProfissionalSaude")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdProfissionalSaude"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CodRegProf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.HasKey("IdProfissionalSaude");

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("ProfissionaisSaude");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("int");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdPessoa")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Agendamento", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("IdCriadoPorUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGHSS.Api.Models.Paciente", "Paciente")
                        .WithMany()
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SGHSS.Api.Models.ProfissionalSaude", "ProfissionalSaude")
                        .WithMany()
                        .HasForeignKey("IdProfissionalSaude")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("Paciente");

                    b.Navigation("ProfissionalSaude");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Paciente", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Pessoa", "Pessoa")
                        .WithOne("Paciente")
                        .HasForeignKey("SGHSS.Api.Models.Paciente", "IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Pagamento", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Agendamento", "Agendamento")
                        .WithOne()
                        .HasForeignKey("SGHSS.Api.Models.Pagamento", "IdAgendamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("SGHSS.Api.Models.ProfissionalSaude", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Pessoa", "Pessoa")
                        .WithOne("ProfissionalSaude")
                        .HasForeignKey("SGHSS.Api.Models.ProfissionalSaude", "IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Usuario", b =>
                {
                    b.HasOne("SGHSS.Api.Models.Pessoa", "Pessoa")
                        .WithOne("Usuario")
                        .HasForeignKey("SGHSS.Api.Models.Usuario", "IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("SGHSS.Api.Models.Pessoa", b =>
                {
                    b.Navigation("Paciente");

                    b.Navigation("ProfissionalSaude");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
